min(trees$Girth)
max(trees$Girth)
min(trees$Height)
max(trees$Height)
min(trees$Volume)
max(trees$Volume)

trees$GirthF <- cut(trees$Girth, breaks=seq(0,24,3))
trees$HeightF <- cut(trees$Height, breaks=seq(50,100,5))
trees$VolumeF <- cut(trees$Volume, breaks=seq(0,100,20))
summary(trees)
plot(trees$GirthF)
plot(trees$HeightF)
plot(trees$VolumeF)

trees$GirthF <- cut(trees$Girth, breaks=seq(0,25,5))
trees$HeightF <- cut(trees$Height, breaks=seq(50,100,10))
trees$VolumeF <- cut(trees$Volume, breaks=seq(0,100,20))
summary(trees)
plot(trees$GirthF)
plot(trees$HeightF)
plot(trees$VolumeF)
