IncidenciasUCLM <- read.table("https://www.uclm.es/profesorado/licesio/Docencia/ToledoR/Datos/IncidenciasUCLM.csv", header = T, sep = ",") 
head(IncidenciasUCLM)
tail(IncidenciasUCLM)
summary(IncidenciasUCLM$Campus)
summary(IncidenciasUCLM$Tipo)
barplot(summary(IncidenciasUCLM$Campus))
barplot(summary(IncidenciasUCLM$Tipo))
tipoPorCampus <- table(IncidenciasUCLM$Tipo, IncidenciasUCLM$Campus)
barplot(tipoPorCampus, legend = rownames(tipoPorCampus), beside = T)
